server:
  port: 8081
spring:
  cloud:
    server:
      git:
        default-label: config
        uri: https://github.com/Merlinys/Server-Config
        search-paths: config-data
  application:
    name: config-server
